
[MAIN]
DebugMode=0                   ;set to 1 to log everything - Check your resources (ship with =0)
DumpNSToLog_before=0          ;Very verbose but good for debugging - dumps all NS info to log file before Registration
DumpNSToLog_after=0           ;Very verbose but good for debugging - dumps all NS info to log file after Registration
OKtoReport_FinalRegError=0    ;Report general error at end if a registration error was logged
OKtoReport_FinalUnRegError=0  ;Report general error at end if a unregistration error was logged

; Resource Strings

[en] ; English
ErrSt_SysFileNotFound = 'Installation Error. Error reading system file or file not found.|%s'
ErrSt_MSHelp2RTNotFound = 'MS Help 2.x runtime files are not installed on this PC.'
ErrSt_NotAdminMode = 'You must be logged on as an Administrator.'
ErrSt_Extra = 'Installation/registration of Help files cannot proceed.'

Msg_Registering = 'Registering Graphics Server Documentation Files:'
Msg_UnRegistering = 'Unregistering Graphics Server Documentation Files:'
Msg_LoggingNSInfo = 'Logging Namespace Info'
Msg_Registering_Namespaces =  'Registering Namespaces'
Msg_Registering_Titles =  'Registering Titles'
Msg_Registering_Plugins =  'Registering Plug-ins'
Msg_Registering_Filters =  'Registering Filters'
Msg_UnRegistering_Namespaces =  'Unregistering Namespaces'
Msg_UnRegistering_Titles =  'Unregistering Titles'
Msg_UnRegistering_Plugins =  'Unregistering Plug-ins'
Msg_UnRegistering_Filters =  'Unregistering Filters'

Msg_Merging_Namespaces = 'Merging Help Indexes. This may take several minutes'

PopupSt_FinalRegError='There were errors reported while Registering help files.||View Log file?'
PopupSt_FinalUnRegError='There were errors reported while Unregistering help files.||View Log file?'


;------- Register -r switch

[Reg_Namespace]
;<nsName>|<nsColfile>|<nsDesc>
GST.GraphicsServer.1033|GS.HxC|Documentation for Graphics Server .Net

[Reg_Title]
;<nsName>|<TitleID>|<LangId>|<HxS_HelpFile>|<HxI_IndexFile>|<HxQ_QueryFile>|<HxR_AttrQueryFile>|<HxsMediaLoc>|<HxqMediaLoc>|<HxrMediaLoc>|<SampleMediaLoc>
GST.GraphicsServer.1033|GSNet|1033|GSNet.HxS|GSNet.HxS||||||

[Reg_Plugin]
;<nsName_Parent>|<HxT_Parent>|<nsName_Child>|<HxT_Child>|<HxA_Child>
MS.VSCC|_DEFAULT|GST.GraphicsServer.1033|_DEFAULT|GS.HxA
MS.VSCC.2003|_DEFAULT|GST.GraphicsServer.1033|_DEFAULT|GS.HxA
MS.VSIPCC+|_DEFAULT|GST.GraphicsServer.1033|_DEFAULT|GS.HxA

[Reg_Filter]
;<nsName>|<FilterName>|<FilterQueryStr>
MS.VSCC|Graphics Server|("DocSet"="GSNet")
MS.VSCC.2003|Graphics Server|("DocSet"="GSNet")
MS.VSIPCC.v80|Graphics Server|("DocSet"="GSNet")

;------- UnRegister -u switch

[UnReg_Namespace]
;<nsName>
GST.GraphicsServer.1033

[UnReg_Title]
;<nsName>|<TitleID>|<LangId>
GST.GraphicsServer.1033|GSNet|1033

[UnReg_Plugin]
;<nsName_Parent>|<HxT_Parent>|<nsName_Child>|<HxT_Child>|<HxA_Child>
MS.VSCC|_DEFAULT|GST.GraphicsServer.1033|_DEFAULT|GS.HxA
MS.VSCC.2003|_DEFAULT|GST.GraphicsServer.1033|_DEFAULT|GS.HxA
MS.VSIPCC+|_DEFAULT|GST.GraphicsServer.1033|_DEFAULT|GS.HxA

[UnReg_Filter]
;<nsName>|<FilterName>


;------ Merge -m switch

[Merge_Namespace]
MS.VSCC|auto
MS.VSCC.2003|auto
MS.VSIPCC+|auto
; Next line needed because we're plugging into a plugin
MS.VSExpressCC+|auto