//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RelayControlLibrary.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RelayControlLibrary.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] FPGAdata {
            get {
                object obj = ResourceManager.GetObject("FPGAdata", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S0110000000050524F4752414D264441544196
        ///S325000000005CE104005CE10A0054E24C0154E2480154E2500154E2540154E2480154E2480140
        ///S3250000002054E2480154E2480154E2480154E2480154E2480154E2480154E2480154E24801C2
        ///S3250000004054E2480154E2DE7054E2537E54E2480154E2580154E2480154E2480154E2480105
        ///S3250000006054E2480154E2480154E2480154E2480154E2480154E2480154E2480154E2480182
        ///S3250000008054E2688354E2480154E2480154E2480154E2480154E2480154E2488954E2480138
        ///S325000000A054E2608454E2480154E2AF7E54E2480154E2480154E2480154E24F8154E2 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string MasterProcessor {
            get {
                return ResourceManager.GetString("MasterProcessor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S0110000000050524F4752414D264441544196
        ///S325000000005CE104005CE10A0054E25A0154E2560154E25E0154E2620154E2560154E25601EC
        ///S3250000002054E2560154E2560154E2560154E2560154E2560154E2560154E2560154E2560152
        ///S3250000004054E2560154E2E35254E2435F54E2560154E2660154E2560154E2560154E25601F9
        ///S3250000006054E2560154E2560154E2560154E2560154E2560154E2560154E2560154E2560112
        ///S3250000008054E2EB6154E2560154E2560154E2560154E2560154E2560154E2E86654E2560106
        ///S325000000A054E29C6254E2560154E2A25F54E2560154E2560154E2560154E2F85F54E2 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string MasterProcessor_Atlanta_DNP {
            get {
                return ResourceManager.GetString("MasterProcessor_Atlanta_DNP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S0110000000050524F4752414D264441544196
        ///S325000000005CE104005CE10A0054E25A0154E2560154E25E0154E2620154E2560154E25601EC
        ///S3250000002054E2560154E2560154E2560154E2560154E2560154E2560154E2560154E2560152
        ///S3250000004054E2560154E29B5154E2FB5D54E2560154E2660154E2560154E2560154E256018C
        ///S3250000006054E2560154E2560154E2560154E2560154E2560154E2560154E2560154E2560112
        ///S3250000008054E2A36054E2560154E2560154E2560154E2560154E2560154E2A06554E2560198
        ///S325000000A054E2546154E2560154E25A5E54E2560154E2560154E2560154E2B05E54E2 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string MasterProcessor_Atlanta_DNP_GE {
            get {
                return ResourceManager.GetString("MasterProcessor_Atlanta_DNP_GE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S0110000000050524F4752414D264441544196
        ///S325000000005CE104005CE10A0054E25A0154E2560154E25E0154E2620154E2560154E25601EC
        ///S3250000002054E2560154E2560154E2560154E2560154E2560154E2560154E2560154E2560152
        ///S3250000004054E2560154E27D5354E24E6054E2560154E2660154E2560154E2560154E2560152
        ///S3250000006054E2560154E2560154E2560154E2560154E2560154E2560154E2560154E2560112
        ///S3250000008054E21B6554E2560154E2560154E2560154E2560154E2560154E2506A54E2560166
        ///S325000000A054E2046654E2560154E2AD6054E2560154E2560154E2560154E2286354E2 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string MasterProcessor_with_DNP {
            get {
                return ResourceManager.GetString("MasterProcessor_with_DNP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S0110000000050524F4752414D264441544196
        ///S325000000005CE104005CE10A0054E25A0154E2560154E25E0154E2620154E2560154E25601EC
        ///S3250000002054E2560154E2560154E2560154E2560154E2560154E2560154E2560154E2560152
        ///S3250000004054E2560154E2355254E2065F54E2560154E2660154E2560154E2560154E25601E4
        ///S3250000006054E2560154E2560154E2560154E2560154E2560154E2560154E2560154E2560112
        ///S3250000008054E2D36354E2560154E2560154E2560154E2560154E2560154E2086954E25601F9
        ///S325000000A054E2BC6454E2560154E2655F54E2560154E2560154E2560154E2E06154E2 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string MasterProcessor_with_DNP_GE {
            get {
                return ResourceManager.GetString("MasterProcessor_with_DNP_GE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S0110000000050524F4752414D264441544196
        ///S325000000005CE104005CE10A0054E2860254E2820254E28A0254E28E0254E2820254E28202DE
        ///S3250000002054E2820254E2820254E2820254E2820254E2820254E2820254E2820254E28202EA
        ///S3250000004054E2820254E23D6454E2E96A54E2820254E2920254E2820254E2820254E28202CE
        ///S3250000006054E2820254E2820254E2820254E2820254E2820254E2820254E2820254E28202AA
        ///S3250000008054E2227154E2820254E2820254E2820254E2820254E2820254E2A77754E28202E1
        ///S325000000A054E21A7254E2820254E25F6B54E2820254E2820254E2820254E2AB6E54E2 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string MasterProcessor_with_DNP_GE_SMUD {
            get {
                return ResourceManager.GetString("MasterProcessor_with_DNP_GE_SMUD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S0110000000050524F4752414D264441544196
        ///S325000000005CE104005CE10A0054E2580154E2540154E25C0154E2600154E2540154E25401F8
        ///S3250000002054E2540154E2540154E2540154E2540154E2540154E2540154E2540154E2540162
        ///S3250000004054E2540154E21F6854E2F07454E2540154E2640154E2540154E2540154E25401F1
        ///S3250000006054E2540154E2540154E2540154E2540154E2540154E2540154E2540154E2540122
        ///S3250000008054E2B97954E2540154E2540154E2540154E2540154E2540154E2FA7E54E2540102
        ///S325000000A054E2A27A54E2540154E24B7554E2540154E2540154E2540154E2C67754E2 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string MasterProcessor_with_DNP_PLC {
            get {
                return ResourceManager.GetString("MasterProcessor_with_DNP_PLC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S0110000000050524F4752414D264441544196
        ///S325000000005CE104005CE10A0054E2560154E2520154E25A0154E25E0154E2520154E2520104
        ///S3250000002054E2520154E2520154E2520154E2520154E2520154E2520154E2520154E2520172
        ///S3250000004054E2520154E20D6354E2B96954E2520154E2620154E2520154E2520154E2520156
        ///S3250000006054E2520154E2520154E2520154E2520154E2520154E2520154E2520154E2520132
        ///S3250000008054E2F26F54E2520154E2520154E2520154E2520154E2520154E2777654E252016A
        ///S325000000A054E2EA7054E2520154E22F6A54E2520154E2520154E2520154E27B6D54E2 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string MasterProcessor_with_DNP_SMUD {
            get {
                return ResourceManager.GetString("MasterProcessor_with_DNP_SMUD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S0110000000050524F4752414D264441544196
        ///S325000000005CE104005CE10A0054E24C0154E2480154E2500154E2540154E2480154E2480140
        ///S3250000002054E2480154E2480154E2480154E2480154E2480154E2480154E2480154E24801C2
        ///S3250000004054E2480154E2DD7054E2527E54E2480154E2580154E2480154E2480154E2480107
        ///S3250000006054E2480154E2480154E2480154E2480154E2480154E2480154E2480154E2480182
        ///S3250000008054E2678354E2480154E2480154E2480154E2480154E2480154E2478954E248013A
        ///S325000000A054E25F8454E2480154E2AE7E54E2480154E2480154E2480154E24E8154E2 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string MasterProcessorChicago {
            get {
                return ResourceManager.GetString("MasterProcessorChicago", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S0110000000050524F4752414D264441544196
        ///S325000000005CE104005CE10A0054E24C0154E2480154E2500154E2540154E2480154E2480140
        ///S3250000002054E2480154E2480154E2480154E2480154E2480154E2480154E2480154E24801C2
        ///S3250000004054E2480154E2F27054E2677E54E2480154E2580154E2480154E2480154E24801DD
        ///S3250000006054E2480154E2480154E2480154E2480154E2480154E2480154E2480154E2480182
        ///S3250000008054E27C8354E2480154E2480154E2480154E2480154E2480154E25C8954E2480110
        ///S325000000A054E2748454E2480154E2C37E54E2480154E2480154E2480154E2638154E2 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string MasterProcessorMadison {
            get {
                return ResourceManager.GetString("MasterProcessorMadison", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S0110000000050524F4752414D264441544196
        ///S3250000000054E25A0154E25A0154E2080154E2040154E20C0154E2100154E2040154E204013E
        ///S3250000002054E2040154E2040154E2040154E2040154E2040154E2040154E2040154E20401E2
        ///S3250000004054E2040154E2F73154E2603254E2040154E2140154E2040154E2040154E2040102
        ///S3250000006054E2040154E2040154E2040154E2040154E2040154E2040154E2040154E20401A2
        ///S3250000008054E2BF7E54E2040154E2040154E2040154E2040154E2040154E2040154E204014A
        ///S325000000A054E2967C54E2040154E2040154E2040154E2040154E2040154E2040154E2 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string RelayProcessor {
            get {
                return ResourceManager.GetString("RelayProcessor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S0110000000050524F4752414D264441544196
        ///S3250000000054E25A0154E25A0154E2080154E2040154E20C0154E2100154E2040154E204013E
        ///S3250000002054E2040154E2040154E2040154E2040154E2040154E2040154E2040154E20401E2
        ///S3250000004054E2040154E2F73154E2603254E2040154E2140154E2040154E2040154E2040102
        ///S3250000006054E2040154E2040154E2040154E2040154E2040154E2040154E2040154E20401A2
        ///S3250000008054E2EC7E54E2040154E2040154E2040154E2040154E2040154E2040154E204011D
        ///S325000000A054E2C37C54E2040154E2040154E2040154E2040154E2040154E2040154E2 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string RelayProcessorAtlanta {
            get {
                return ResourceManager.GetString("RelayProcessorAtlanta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S0110000000050524F4752414D264441544196
        ///S3250000000054E2680154E2680154E2160154E2120154E21A0154E21E0154E2120154E21201CE
        ///S3250000002054E2120154E2120154E2120154E2120154E2120154E2120154E2120154E2120172
        ///S3250000004054E2120154E2BA3B54E2233C54E2120154E2220154E2120154E2120154E2120114
        ///S3250000006054E2120154E2120154E2120154E2120154E2120154E2120154E2120154E2120132
        ///S3250000008054E2758854E2120154E2120154E2120154E2120154E2120154E2120154E2120128
        ///S325000000A054E24C8654E2120154E2120154E2120154E2120154E2120154E2120154E2 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string RelayProcessorAtlantaGE {
            get {
                return ResourceManager.GetString("RelayProcessorAtlantaGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S0110000000050524F4752414D264441544196
        ///S3250000000054E2680154E2680154E2160154E2120154E21A0154E21E0154E2120154E21201CE
        ///S3250000002054E2120154E2120154E2120154E2120154E2120154E2120154E2120154E2120172
        ///S3250000004054E2120154E2BA3B54E2233C54E2120154E2220154E2120154E2120154E2120114
        ///S3250000006054E2120154E2120154E2120154E2120154E2120154E2120154E2120154E2120132
        ///S3250000008054E2488854E2120154E2120154E2120154E2120154E2120154E2120154E2120155
        ///S325000000A054E21F8654E2120154E2120154E2120154E2120154E2120154E2120154E2 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string RelayProcessorGE {
            get {
                return ResourceManager.GetString("RelayProcessorGE", resourceCulture);
            }
        }
    }
}
