//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RelayControlLibrary.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RelayControlLibrary.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] FPGAdata {
            get {
                object obj = ResourceManager.GetObject("FPGAdata", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S0110000000050524F4752414D264441544196
        ///S325000000005CE104005CE10A0054E24C0154E2480154E2500154E2540154E2480154E2480140
        ///S3250000002054E2480154E2480154E2480154E2480154E2480154E2480154E2480154E24801C2
        ///S3250000004054E2480154E2277054E29C7D54E2480154E2580154E2480154E2480154E2480174
        ///S3250000006054E2480154E2480154E2480154E2480154E2480154E2480154E2480154E2480182
        ///S3250000008054E2B18254E2480154E2480154E2480154E2480154E2480154E2598954E24801DF
        ///S325000000A054E2A98354E2480154E2F87D54E2480154E2480154E2480154E2988054E2 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string MasterProcessor {
            get {
                return ResourceManager.GetString("MasterProcessor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S0110000000050524F4752414D264441544196
        ///S325000000005CE104005CE10A0054E25A0154E2560154E25E0154E2620154E2560154E25601EC
        ///S3250000002054E2560154E2560154E2560154E2560154E2560154E2560154E2560154E2560152
        ///S3250000004054E2560154E25E5154E22F5E54E2560154E2660154E2560154E2560154E2560194
        ///S3250000006054E2560154E2560154E2560154E2560154E2560154E2560154E2560154E2560112
        ///S3250000008054E2FC6254E2560154E2560154E2560154E2560154E2560154E2F76854E25601E3
        ///S325000000A054E2E56354E2560154E28E5E54E2560154E2560154E2560154E2096154E2 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string MasterProcessor_with_DNP {
            get {
                return ResourceManager.GetString("MasterProcessor_with_DNP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S0110000000050524F4752414D264441544196
        ///S325000000005CE104005CE10A0054E25A0154E2560154E25E0154E2620154E2560154E25601EC
        ///S3250000002054E2560154E2560154E2560154E2560154E2560154E2560154E2560154E2560152
        ///S3250000004054E2560154E25E5154E22F5E54E2560154E2660154E2560154E2560154E2560194
        ///S3250000006054E2560154E2560154E2560154E2560154E2560154E2560154E2560154E2560112
        ///S3250000008054E2FC6254E2560154E2560154E2560154E2560154E2560154E2F76854E25601E3
        ///S325000000A054E2E56354E2560154E28E5E54E2560154E2560154E2560154E2096154E2 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string MasterProcessor_with_DNP_GE {
            get {
                return ResourceManager.GetString("MasterProcessor_with_DNP_GE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S0110000000050524F4752414D264441544196
        ///S325000000005CE104005CE10A0054E2860254E2820254E28A0254E28E0254E2820254E28202DE
        ///S3250000002054E2820254E2820254E2820254E2820254E2820254E2820254E2820254E28202EA
        ///S3250000004054E2820254E23D6454E2E96A54E2820254E2920254E2820254E2820254E28202CE
        ///S3250000006054E2820254E2820254E2820254E2820254E2820254E2820254E2820254E28202AA
        ///S3250000008054E2227154E2820254E2820254E2820254E2820254E2820254E2A77754E28202E1
        ///S325000000A054E21A7254E2820254E25F6B54E2820254E2820254E2820254E2AB6E54E2 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string MasterProcessor_with_DNP_GE_SMUD {
            get {
                return ResourceManager.GetString("MasterProcessor_with_DNP_GE_SMUD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S0110000000050524F4752414D264441544196
        ///S325000000005CE104005CE10A0054E2580154E2540154E25C0154E2600154E2540154E25401F8
        ///S3250000002054E2540154E2540154E2540154E2540154E2540154E2540154E2540154E2540162
        ///S3250000004054E2540154E2836754E2547454E2540154E2640154E2540154E2540154E254012A
        ///S3250000006054E2540154E2540154E2540154E2540154E2540154E2540154E2540154E2540122
        ///S3250000008054E21D7954E2540154E2540154E2540154E2540154E2540154E2247F54E2540173
        ///S325000000A054E2067A54E2540154E2AF7454E2540154E2540154E2540154E22A7754E2 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string MasterProcessor_with_DNP_PLC {
            get {
                return ResourceManager.GetString("MasterProcessor_with_DNP_PLC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S0110000000050524F4752414D264441544196
        ///S325000000005CE104005CE10A0054E2560154E2520154E25A0154E25E0154E2520154E2520104
        ///S3250000002054E2520154E2520154E2520154E2520154E2520154E2520154E2520154E2520172
        ///S3250000004054E2520154E20D6354E2B96954E2520154E2620154E2520154E2520154E2520156
        ///S3250000006054E2520154E2520154E2520154E2520154E2520154E2520154E2520154E2520132
        ///S3250000008054E2F26F54E2520154E2520154E2520154E2520154E2520154E2777654E252016A
        ///S325000000A054E2EA7054E2520154E22F6A54E2520154E2520154E2520154E27B6D54E2 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string MasterProcessor_with_DNP_SMUD {
            get {
                return ResourceManager.GetString("MasterProcessor_with_DNP_SMUD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S0110000000050524F4752414D264441544196
        ///S325000000005CE104005CE10A0054E24C0154E2480154E2500154E2540154E2480154E2480140
        ///S3250000002054E2480154E2480154E2480154E2480154E2480154E2480154E2480154E24801C2
        ///S3250000004054E2480154E2267054E29B7D54E2480154E2580154E2480154E2480154E2480176
        ///S3250000006054E2480154E2480154E2480154E2480154E2480154E2480154E2480154E2480182
        ///S3250000008054E2B08254E2480154E2480154E2480154E2480154E2480154E2588954E24801E1
        ///S325000000A054E2A88354E2480154E2F77D54E2480154E2480154E2480154E2978054E2 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string MasterProcessorChicago {
            get {
                return ResourceManager.GetString("MasterProcessorChicago", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S0110000000050524F4752414D264441544196
        ///S3250000000054E25A0154E25A0154E2080154E2040154E20C0154E2100154E2040154E204013E
        ///S3250000002054E2040154E2040154E2040154E2040154E2040154E2040154E2040154E20401E2
        ///S3250000004054E2040154E2E23154E24B3254E2040154E2140154E2040154E2040154E204012C
        ///S3250000006054E2040154E2040154E2040154E2040154E2040154E2040154E2040154E20401A2
        ///S3250000008054E2B17E54E2040154E2040154E2040154E2040154E2040154E2040154E2040158
        ///S325000000A054E2887C54E2040154E2040154E2040154E2040154E2040154E2040154E2 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string RelayProcessor {
            get {
                return ResourceManager.GetString("RelayProcessor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S0110000000050524F4752414D264441544196
        ///S3250000000054E2680154E2680154E2160154E2120154E21A0154E21E0154E2120154E21201CE
        ///S3250000002054E2120154E2120154E2120154E2120154E2120154E2120154E2120154E2120172
        ///S3250000004054E2120154E2A53B54E20E3C54E2120154E2220154E2120154E2120154E212013E
        ///S3250000006054E2120154E2120154E2120154E2120154E2120154E2120154E2120154E2120132
        ///S3250000008054E23A8854E2120154E2120154E2120154E2120154E2120154E2120154E2120163
        ///S325000000A054E2118654E2120154E2120154E2120154E2120154E2120154E2120154E2 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string RelayProcessorGE {
            get {
                return ResourceManager.GetString("RelayProcessorGE", resourceCulture);
            }
        }
    }
}
