//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34003
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RelayControlLibrary.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RelayControlLibrary.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] FPGAdata {
            get {
                object obj = ResourceManager.GetObject("FPGAdata", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S0110000000050524F4752414D264441544196
        ///S325000000005CE104005CE10A0054E2360154E2320154E23A0154E23E0154E2320154E23201C4
        ///S3250000002054E2320154E2320154E2320154E2320154E2320154E2320154E2320154E2320172
        ///S3250000004054E2320154E22F6754E2B85A54E2320154E2420154E2320154E2320154E2320100
        ///S3250000006054E2320154E2320154E2320154E2320154E2320154E2320154E2320154E2320132
        ///S3250000008054E2746054E2320154E2320154E2320154E2320154E2320154E28C6654E23201B2
        ///S325000000A054E25D6154E2320154E21F5B54E2320154E2320154E2320154E2245E54E2 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string MasterProcessor {
            get {
                return ResourceManager.GetString("MasterProcessor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S0110000000050524F4752414D264441544196
        ///S325000000005CE104005CE10A0054E23C0154E2380154E2400154E2440154E2380154E23801A0
        ///S3250000002054E2380154E2380154E2380154E2380154E2380154E2380154E2380154E2380142
        ///S3250000004054E2380154E2917C54E2398354E2380154E2480154E2380154E2380154E23801BB
        ///S3250000006054E2380154E2380154E2380154E2380154E2380154E2380154E2380154E2380102
        ///S3250000008054E26E8954E2380154E2380154E2380154E2380154E2380154E2F38F54E23801DB
        ///S325000000A054E2668A54E2380154E2AF8354E2380154E2380154E2380154E2FB8654E2 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string MasterProcessor_with_DNP {
            get {
                return ResourceManager.GetString("MasterProcessor_with_DNP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S0110000000050524F4752414D264441544196
        ///S325000000005CE104005CE10A0054E23C0154E2380154E2400154E2440154E2380154E23801A0
        ///S3250000002054E2380154E2380154E2380154E2380154E2380154E2380154E2380154E2380142
        ///S3250000004054E2380154E2917C54E2398354E2380154E2480154E2380154E2380154E23801BB
        ///S3250000006054E2380154E2380154E2380154E2380154E2380154E2380154E2380154E2380102
        ///S3250000008054E26E8954E2380154E2380154E2380154E2380154E2380154E2F38F54E23801DB
        ///S325000000A054E2668A54E2380154E2AF8354E2380154E2380154E2380154E2FB8654E2 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string MasterProcessor_with_DNP_GE {
            get {
                return ResourceManager.GetString("MasterProcessor_with_DNP_GE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S0110000000050524F4752414D264441544196
        ///S3250000000054E2541954E2541954E2F60054E2F20054E2FA0054E2FE0054E2F20054E2F2008C
        ///S3250000002054E2F20054E2F20054E2F20054E2F20054E2F20054E2F20054E2F20054E2F2007A
        ///S3250000004054E2F20054E2C11954E2211A54E2F20054E2020154E2F20054E2F20054E2F20018
        ///S3250000006054E2F20054E2F20054E2F20054E2F20054E2F20054E2F20054E2F20054E2F2003A
        ///S3250000008054E2D14254E2F20054E2F20054E2F20054E2F20054E2F20054E2F20054E2F200F9
        ///S325000000A054E2374154E2F20054E2F20054E2F20054E2F20054E2F20054E2F20054E2 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string RelayProcessor {
            get {
                return ResourceManager.GetString("RelayProcessor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S0110000000050524F4752414D264441544196
        ///S3250000000054E2571954E2571954E2000154E2FC0054E2040154E2080154E2FC0054E2FC0047
        ///S3250000002054E2FC0054E2FC0054E2FC0054E2FC0054E2FC0054E2FC0054E2FC0054E2FC002A
        ///S3250000004054E2FC0054E2C41954E2241A54E2FC0054E20C0154E2FC0054E2FC0054E2FC00D6
        ///S3250000006054E2FC0054E2FC0054E2FC0054E2FC0054E2FC0054E2FC0054E2FC0054E2FC00EA
        ///S3250000008054E2A54254E2FC0054E2FC0054E2FC0054E2FC0054E2FC0054E2FC0054E2FC00DF
        ///S325000000A054E20B4154E2FC0054E2FC0054E2FC0054E2FC0054E2FC0054E2FC0054E2 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string RelayProcessorGE {
            get {
                return ResourceManager.GetString("RelayProcessorGE", resourceCulture);
            }
        }
    }
}
